version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - python/install-packages
workflows:
  example-workflow:
    jobs:
      - example-job